name: main

on:
  workflow_dispatch:
  schedule:
  - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - run: npm ci
    - name: main
      run: npm run generate
    - name: Update README.md
      run: |
        git config --global user.email "lthoquyen2002@gmail.com"
        git config --global user.name "snsarvn"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
